FAST-ER: tree_element Class Reference
tree_element Class Reference
[Tree representation.]
#include <faster_tree.h>
Detailed Description
This struct represents a node of the tree, and has pointers to other structs, thereby representing a branch or the entire tree.
Definition at line 39 of file faster_tree.h.
Public Member Functions
std::pair
< CVD::ImageRef,
CVD::ImageRef > bbox () const
int num_nodes () const
bool is_leaf () const
std::pair
< tree_element *,
bool > nth_element (int t)
block_bytecode make_fast_detector (int xsize) const
int detect_corner (const CVD::Image< CVD::byte > &im, CVD::ImageRef pos, int b) const
tree_element * copy ()
void print (std::ostream &o, std::string ind=" ") const
~tree_element ()
tree_element (bool b)
tree_element (tree_element *a, tree_element *b, tree_element *c, int i)
Public Attributes
tree_element * lt
tree_element * eq
tree_element * gt
bool is_corner
int offset_index
Private Member Functions
void make_fast_detector_o (std::vector< block_bytecode::fast_detector_bit > &v, int n, int xsize, int N, bool invert) const
std::pair
< tree_element *,
bool > nth_element (int target, int &n, bool eq_branch)
int detect_corner_oriented (const CVD::Image< CVD::byte > &im, CVD::ImageRef pos, int b, int n, bool invert) const
Constructor & Destructor Documentation
tree_element::~tree_element () [inline]
Destruct the tree node.
This destructs all child nodes, so deleting a tree a deep modification operation.
Definition at line 366 of file faster_tree.h.
        {
            delete lt;
            delete eq;
            delete gt;
        }
tree_element::tree_element (bool b) [inline]
Construct a leaf-node.
Parameters:
b Class of the node
Definition at line 375 of file faster_tree.h.
        :lt(0),eq(0),gt(0),is_corner(b),offset_index(0)
        {}
tree_element::tree_element (tree_element * a, tree_element * b, tree_element * c, int i) [inline]
Construct a non-leaf tree node.
Parameters:
a Less-Than branch of tree
b Equal branch of tree
c Greater-Than branch of tree
i Pixel number to examine.
Definition at line 384 of file faster_tree.h.
        :lt(a),eq(b),gt(c),is_corner(0),offset_index(i)
        {}
Member Function Documentation
std::pair<CVD::ImageRef, CVD::ImageRef> tree_element::bbox () const [inline]
This returns the bounding box of the detector.
Definition at line 50 of file faster_tree.h.
References offsets_bbox.
Referenced by tree_detect_corners(), and tree_detect_corners_all().
        {
            return offsets_bbox;
        }
int tree_element::num_nodes () const [inline]
This returns the number of nodes in the tree.
Definition at line 56 of file faster_tree.h.
References eq, gt, lt, and num_nodes().
Referenced by learn_detector(), and num_nodes().
        {
            if(eq == NULL)
                return 1;
            else
                return 1 + lt->num_nodes() + eq->num_nodes() + gt->num_nodes();
        }
bool tree_element::is_leaf () const [inline]
Is the node a leaf?
Definition at line 66 of file faster_tree.h.
References eq.
Referenced by learn_detector(), and make_fast_detector_o().
        {
            return eq == NULL;
        }
std::pair<tree_element*,bool> tree_element::nth_element (int t) [inline]
Return a given numbered element of the tree.
Elements are numbered by depth-first traversal.
Parameters:
t Element number to return
Returns:
pointer to the t'th element, and a flag indicating whether it's the direct child of an eq branch.
Definition at line 76 of file faster_tree.h.
Referenced by learn_detector().
        {
            //The root node can not be a corner.
            //Otherwise the strength would be inf.
            int n=0;
            return nth_element(t, n, true);
        }
std::pair<tree_element*, bool> tree_element::nth_element (int target, int & n, bool eq_branch) [inline, private]
Select the n'th elment of the tree.
Definition at line 232 of file faster_tree.h.
        {
            using tag::operator<<;
            #ifndef NDEBUG
                if(!( (eq==0 && lt == 0 && gt == 0) || (eq!=0 && lt!=0 &&gt != 0)))
                {
                    std::clog << "Error: corrupted tree\n";
                    std::clog << tag::print << "lt" << lt;
                    std::clog << tag::print << "eq" << eq;
                    std::clog << tag::print << "gt" << gt;
                    abort();
                }
            #endif
            if(target == n)
                return std::make_pair(this, eq_branch);
            else
            {
                n++;
                tree_element * r;
                bool e;
                if(eq == 0)
                    return std::make_pair(r=0,eq_branch);
                else
                {
                    tag::rpair(r, e) = lt->nth_element(target, n, false);
                    if(r != NULL)
                        return std::make_pair(r, e);
                    tag::rpair(r, e) = eq->nth_element(target, n, true);
                    if(r != NULL)
                        return std::make_pair(r, e);
                    return gt->nth_element(target, n, false);
                }
            }
        }
int tree_element::detect_corner_oriented (const CVD::Image< CVD::byte > & im, CVD::ImageRef pos, int b, int n, bool invert) const [inline, private]
Apply the tree to detect a corner in a single form.
Parameters:
im Image in which to detect corners
pos position at which to perform detection
b Threshold
n tree orientation to use (index in to offsets)
invert Whether to perform an intensity inversion
Returns:
0 for no corner, otherwise smallet amount by which a test passed.
Definition at line 282 of file faster_tree.h.
References detect_corner_oriented(), is_corner(), and offsets.
Referenced by detect_corner_oriented().
        {
            //Return number that threshold would have to be increased to in
            //order to change the outcome
            if(eq== NULL)
                return is_corner * INT_MAX;
            else
            {
                int c = im[pos];
                int p = im[pos + offsets[n][offset_index]];
                const tree_element* llt = lt;
                const tree_element* lgt = gt;
                if(invert)
                    std::swap(llt, lgt);
                if(p > c+b)
                    return std::min(p-(c+b), lgt->detect_corner_oriented(im, pos, b, n, invert));
                else if(p < c-b)
                    return std::min((c-b)-p, llt->detect_corner_oriented(im, pos, b, n, invert));
                else
                    return eq->detect_corner_oriented(im, pos, b, n, invert);
            }
        }
int tree_element::detect_corner (const CVD::Image< CVD::byte > & im, CVD::ImageRef pos, int b) const [inline]
Apply the tree in all forms to detect a corner.
Parameters:
im CVD::Image in which to detecto corners
pos position at which to perform detection
b Threshold
Returns:
0 for no corner, otherwise smallet amount by which a test passed.
Definition at line 318 of file faster_tree.h.
References invert(), and offsets.
Referenced by tree_detect_corners(), and tree_detect_corners_all().
        {
            for(int invert=0; invert <2; invert++)
                for(unsigned int i=0; i < offsets.size(); i++)
                {
                    int n = detect_corner_oriented(im, pos, b, i, invert);
                    if(n)
                        return n;
                }
            return 0;
        }
tree_element* tree_element::copy () [inline]
Deep copy the tree.
Definition at line 331 of file faster_tree.h.
References copy(), eq, gt, and lt.
Referenced by copy(), and learn_detector().
        {
            tree_element* t = new tree_element(*this);
            if(eq != NULL)
            {
                t->lt = lt->copy();
                t->gt = gt->copy();
                t->eq = eq->copy();
            }
            return t;
        }
void tree_element::print (std::ostream & o, std::string ind = " ") const [inline]
Serialize the tree.
Parameters:
o Stream to serialize to.
ind The indent level to use for the current branch.
Definition at line 348 of file faster_tree.h.
References is_corner().
Referenced by learn_detector(), and run_learn_detector().
        {
            using tag::operator<<;
            if(eq == NULL)
                o << ind << tag::print << "Is corner: " << is_corner << this << lt << eq << gt;
            else
            {
                o << ind << tag::print << offset_index << this << lt << eq << gt;
                lt->print(o, ind + "  ");
                eq->print(o, ind + "  ");
                gt->print(o, ind + "  ");
            }
        }
Member Data Documentation
tree_element* tree_element::lt
Branch of the tree to take if the offset pixel is much darker than the centre.
Definition at line 42 of file faster_tree.h.
Referenced by copy(), learn_detector(), make_fast_detector(), make_fast_detector_o(), and num_nodes().
tree_element* tree_element::eq
Branch of the tree to take if the offset pixel is much brighter than the centre.
Definition at line 43 of file faster_tree.h.
Referenced by copy(), is_leaf(), learn_detector(), make_fast_detector_o(), and num_nodes().
tree_element* tree_element::gt
Branch of the tree to take otherwise.
Definition at line 44 of file faster_tree.h.
Referenced by copy(), learn_detector(), make_fast_detector(), make_fast_detector_o(), and num_nodes().
bool tree_element::is_corner
If the node is a leaf, then this is its attribute.
Definition at line 45 of file faster_tree.h.
Referenced by learn_detector(), and make_fast_detector_o().
int tree_element::offset_index
Offset number of the pixel to examine. This indexes offsets[x].
Definition at line 46 of file faster_tree.h.
Referenced by learn_detector(), and make_fast_detector_o().
The documentation for this class was generated from the following file:
faster_tree.h