FAST-ER: extract_features.cc File Reference
extract_features.cc File Reference
Detailed Description
Main file for the extract_features executable.
extract_features [--VAR VAL] [--exec FILE] IMAGE1 [IMAGE2 ...]
This program loads a learned FAST-ER tree and extracts features so that an accelerated tree can be learned. The output is is suitable for consumption by learn_fast_tree.
The program accpets standard GVars3 commandline arguments, and the default parameters are contained in extract_features.cfg :
offsets.min_radius=2.0    //This must be the same as the value used in training
offsets.max_radius=4.2    //This must be the same as the value used in training
detector=best_faster.tree //File containing the learned FAST-ER tree
threshold=30              //Threshold at which to detect corners
skip=2                    //Skip this many pixels in the X and Y direction when extracting non-corners
debug.verify_detections=0
The images from which features should be extracted are specified on the commandline.
Definition in file extract_features.cc.
#include <gvars3/instances.h>
#include <cvd/image_io.h>
#include <stdint.h>
#include <map>
#include <iterator>
#include <string>
#include "offsets.h"
#include "faster_tree.h"
Functions
void extract_feature (string &s, const BasicImage< byte > &im, const ImageRef &pos, int barrier, int o, bool invert_sense)
int main (int argc, char **argv)
Variables
static const char BrighterFlag = 'b'
static const char DarkerFlag = 'd'
static const char SimilarFlag = 's'
Function Documentation
void extract_feature (string & s, const BasicImage< byte > & im, const ImageRef & pos, int barrier, int o, bool invert_sense)
Extracts a feature from an image.
Parameters:
s String to extract feature in to
im Image to extract feature from
pos Location to extract feature from
barrier Threshold used to compute feature
o Index in to offsets (i.e. feature orientation) to use
invert_sense Whether or not to invert the extracted feature
Definition at line 67 of file extract_features.cc.
References BrighterFlag, DarkerFlag, num_offsets, offsets, and SimilarFlag.
Referenced by main().
{
    int cb = im[pos] + barrier;
    int c_b = im[pos] - barrier;
    for(int i=0; i < num_offsets; i++)
    {
        int pix = im[pos + offsets[o][i]];
        if(pix > cb)
            if(invert_sense == false)
                s[i] = BrighterFlag;
            else
                s[i] = DarkerFlag;
        else if(pix < c_b)
            if(invert_sense == false)
                s[i] = DarkerFlag;
            else
                s[i] = BrighterFlag;
        else
            s[i] = SimilarFlag;
    }
}
int main (int argc, char ** argv)
Driving program.
Parameters:
argc Number of commandline arguments
argv List of commandline arguments. Contains GVars3 arguments, and images to process.
Definition at line 94 of file extract_features.cc.
References create_offsets(), extract_feature(), is_corner(), load_a_tree(), num_offsets, offsets, and offsets_bbox.
{
    //The usual initialization.
    GUI.LoadFile("extract_features.cfg");
    int lastarg = GUI.parseArguments(argc, argv);
    create_offsets();
    //Store corners and noncorners by the string representing the feature.
    map<string, uint64_t> corners, non_corners;
    //Scratch string of the correct length for extracting features in to.
    string scratch(num_offsets, '.');
    //Don't bother examining points outside this border.
    int border = max(max(offsets_bbox.first.x, offsets_bbox.first.y), max(offsets_bbox.second.x, offsets_bbox.second.y));
    int threshold = GV3::get<int>("threshold", 30);
    string fname=GV3::get<string>("detector", "best_faster.tree");
    //Load a detector from a tree file
    tree_element* faster_detector;
    ifstream i;
    i.open(fname.c_str());
    if(!i.good())
    {
        cerr << "Error: " << fname << ": " << strerror(errno) << endl;
        exit(1);
    }
    try{
        faster_detector = load_a_tree(i);
    }
    catch(ParseError p)
    {
        cerr << "Parse error in " << fname << endl;
        exit(1);
    }
    //Iterate over all images, extracting features
    for(int i=lastarg; i < argc; i++)
    {
        try{
            Image<byte> im = img_load(argv[i]);
            for(int r=border; r < im.size().y - border; r++)
                for(int c=border; c < im.size().x - border; c++)
                {
                    ImageRef pos(c,r);
                    //Test for cornerness
                    bool is_corner = faster_detector->detect_corner(im, pos, threshold);
                    //Iterate over all feature orientations and inversions,
                    //extracting the reatures, and inserting them in to the
                    //correct bin
                    for(unsigned int k=0; k < offsets.size(); k++)
                        for(int l=0; l < 2; l++)
{
                            extract_feature(scratch, im, pos, threshold, k, l);
                            if(is_corner)
{
                                corners[scratch]++;
                                if(non_corners.count(scratch))
{
                                    cerr << "Fatal error! extracted corner has an identical non-corner!\n";
                                    cerr << "Are your offsets correct?\n";
                                    exit(1);
                                }
                            }
                            else
{
                                non_corners[scratch]++;
                                if(corners.count(scratch))
{
                                    cerr << "Fatal error! extracted non-corner has an identical corner!\n";
                                    cerr << "Are your offsets correct?\n";
                                    exit(1);
                                }
                            }
                        }
                }
            cerr << "Processed " << argv[i] << endl;
        }
        catch(Exceptions::All e)
        {
            cerr << "Failed to load " << argv[i] << ": " << e.what << endl;
        }
    }
    cout << num_offsets << endl;
    copy(offsets[0].begin(), offsets[0].end(), ostream_iterator<ImageRef>(cout, " "));
    cout << endl;
    for(map<string, uint64_t>::iterator i=corners.begin(); i != corners.end(); i++)
        cout << i->first << " " << i->second << " 1" << endl;
    for(map<string, uint64_t>::iterator i=non_corners.begin(); i != non_corners.end(); i++)
        cout << i->first << " " << i->second << " 0" << endl;
}
Variable Documentation
const char BrighterFlag = 'b' [static]
Character code for pixels significantly brighter than the centre.
Definition at line 56 of file extract_features.cc.
Referenced by extract_feature().
const char DarkerFlag = 'd' [static]
Character code for pixels significantly darker than the centre.
Definition at line 57 of file extract_features.cc.
Referenced by extract_feature().
const char SimilarFlag = 's' [static]
Character code for pixels similar to the centre.
Definition at line 58 of file extract_features.cc.
Referenced by extract_feature().