FAST-ER: fast_N_features.cc File Reference
fast_N_features.cc File Reference
Detailed Description
Main file for the fant_N_features executable.
./fast_N_features [--NUM N] | ./learn_fast_tree
This program generates a list of all possible FAST-N features in an output format suitable for consumption by learn_fast_tree. The program accepts standarg GVars3 commandline arguments. The only useful argument is N which specifies the N for which FAST-N features should be generated.
Definition in file fast_N_features.cc.
#include <iostream>
#include <gvars3/instances.h>
Functions
bool is_corner (const char *str, int num_for_corner, char type)
int main (int argc, char **argv)
Function Documentation
bool is_corner (const char * str, int num_for_corner, char type) [inline]
Determine if a string has the properties of a FAST-N corner.
In other words, if it has enough consecutive characters of the correct type. This function assumes that the string wraps in a circular manner.
Parameters:
str String to test for cornerness.
num_for_corner Number of consecutive characters required for corner
type Character value which must appear consecutively#
Returns:
whether the string is a corner.
Definition at line 52 of file fast_N_features.cc.
Referenced by tree_element::detect_corner_oriented(), load_a_tree(), main(), and tree_element::print().
{
    int num_consecutive=0;
    int first_cons=0;
    for(int i=0; i<16; i++)
    {
        if(str[i] == type)
        {
            num_consecutive++;
            if(num_consecutive == num_for_corner)
                return 1;
        }
        else
        {
            if(num_consecutive == i)
                first_cons=i;
            num_consecutive=0;
        }
    }
    if(first_cons+num_consecutive >=num_for_corner)
        return 1;
    else
        return 0;
}
int main (int argc, char ** argv)
This is the main function for this program.
It generates all possible FAST pixel rings using brute-force and outputs them along with their class and a uniform weighting over all features.
Parameters:
argc Number of commandline arguments
argv List of commandline arguments
Definition at line 86 of file fast_N_features.cc.
References is_corner().
{
    GUI.parseArguments(argc, argv);
    char types[]="bsd.";
    char F[17]="................";
    int a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p;
    cout << 16 << endl;
    cout << "[0 3] [1 3] [2 2] [3 1] [3 0] [3 -1] [2 -2] [1 -3] [0 -3] [-1 -3] [-2 -2] [-3 -1] [-3 0] [-3 1] [-2 2] [-1 3]" << endl;
    int N = GV3::get<int>("N", 9, 1);
    for(a = 0, F[ 0]='b'; a < 3; a++, F[ 0]=types[a])
     for(b = 0, F[ 1]='b'; b < 3; b++, F[ 1]=types[b])
      for(c = 0, F[ 2]='b'; c < 3; c++, F[ 2]=types[c])
       for(d = 0, F[ 3]='b'; d < 3; d++, F[ 3]=types[d])
        for(e = 0, F[ 4]='b'; e < 3; e++, F[ 4]=types[e])
         for(f = 0, F[ 5]='b'; f < 3; f++, F[ 5]=types[f])
          for(g = 0, F[ 6]='b'; g < 3; g++, F[ 6]=types[g])
           for(h = 0, F[ 7]='b'; h < 3; h++, F[ 7]=types[h])
            for(i = 0, F[ 8]='b'; i < 3; i++, F[ 8]=types[i])
             for(j = 0, F[ 9]='b'; j < 3; j++, F[ 9]=types[j])
              for(k = 0, F[10]='b'; k < 3; k++, F[10]=types[k])
               for(l = 0, F[11]='b'; l < 3; l++, F[11]=types[l])
                for(m = 0, F[12]='b'; m < 3; m++, F[12]=types[m])
                 for(n = 0, F[13]='b'; n < 3; n++, F[13]=types[n])
                  for(o = 0, F[14]='b'; o < 3; o++, F[14]=types[o])
                   for(p = 0, F[15]='b'; p < 3; p++, F[15]=types[p])
                    cout << F << " 1 " << (is_corner(F, N, 'b') || is_corner(F, N, 'd')) << endl;
}