FAST-ER: Functions for detecting corners of various types.
Functions for detecting corners of various types.
Classes
struct SearchThreshold
This class wraps a DetectT class with binary_search_threshold and presents is as a DetectN class.
struct Random
Detector which randomly scatters corners around an image.
struct DetectN
A corner detector object which is passed a target number of corners to detect.
struct DetectT
A corner detector object which is passed a threshold.
struct dog
Class wrapping the Difference of Gaussians detector.
struct harrisdog
Class wrapping the Harris-Laplace detector.
struct faster_learn
FAST-ER detector.
struct ShiTomasiDetect
Class wrapping the Harris detector.
struct HarrisDetect
Class wrapping the Shi-Tomasi detector.
struct SUSAN
Class wrapping the SUSAN detector.
Functions
int binary_search_threshold (const Image< byte > &i, vector< ImageRef > &c, unsigned int N, const DetectT &detector)
auto_ptr< DetectN > get_detector ()
void HarrisDetector (const CVD::Image< float > &i, std::vector< std::pair< float, CVD::ImageRef > > &c, unsigned int N, float blur, float sigmas)
Function Documentation
int binary_search_threshold (const Image< byte > & i, vector< ImageRef > & c, unsigned int N, const DetectT & detector)
This takes a detector which requires a threshold and uses binary search to get as close as possible to the requested number of corners.
Parameters:
i The image in which to detect corners.
c The detected corners to be returned.
N The target number of corners.
detector The corner detector.
Definition at line 47 of file detectors.cc.
Referenced by SearchThreshold::operator()().
{
    //Corners for high, low and midpoint thresholds.
    vector<ImageRef> ch, cl, cm;
    //The high and low thresholds.
    unsigned int t_high = 256;
    unsigned int t_low = 0;
    detector(i, ch, t_high);
    detector(i, cl, t_low);
    while(t_high > t_low + 1)
    {
        cm.clear();
        unsigned int t = (t_high + t_low    ) / 2;
        detector(i, cm, t);
        if(cm.size() == N)
        {
            c = cm;
            return t;
        }
        else if(cm.size() < N) //If we detected too few points, then the t is too high
        {
            t_high = t;
            ch = cm;
        }
        else //We detected too many points to t is too low.
        {
            t_low = t;
            cl = cm;
        }
    }
    //Pick the closest
    //If there is ambiguity, go with the lower threshold (more corners).
    //The only reason for this is that the evaluation code in the FAST-ER
    //system uses this rule.
    if( N - ch.size() >= cl.size() - N)
    {
        c = cl;
        return t_low;
    }
    else
    {
        c = ch;
        return t_high;
    }
}
auto_ptr<DetectN> get_detector ()
Very simple factory function for getting detector objects.
Get a corner detector.
Paramaters (including the detector type) are drawn from the GVars database. The parameter "detector" determines the detector type. Valid options are:
random Randomly scatter corners around the image.
dog Difference of Gaussians detector
harrisdog Harris-Laplace (actually implemented as Harris-DoG) detector
harris Harris detector with Gaussian blur
shitomasi Shi-Tomasi detector
susan Reference implementation of the SUSAN detector
fast9 libCVD's builtin FAST-9 detector
fast9old libCVD's builtin FAST-9 detector with the old scoring algorithm, as seen in [Rosten, Drummond 2006].
fast12 libCVD's builtin FAST-12 detector
faster2 A FAST-ER detector loaded from a file containing the tree
Definition at line 156 of file detectors.cc.
Referenced by mmain().
{
    string d = GV3::get<string>("detector", "fast9", 1);
    if(d == "random")
        return auto_ptr<DetectN>(new Random);
    else if(d == "dog")
        return auto_ptr<DetectN>(new dog);
    else if(d == "harrisdog")
        return auto_ptr<DetectN>(new harrisdog);
    else if(d == "shitomasi")
        return auto_ptr<DetectN>(new ShiTomasiDetect);
    else if(d == "harris")
        return auto_ptr<DetectN>(new HarrisDetect);
    #ifdef USESUSAN
        else if(d == "susan")
            return auto_ptr<DetectN>(new SearchThreshold(new SUSAN));
    #endif
    else if(d == "fast9")
        return auto_ptr<DetectN>(new SearchThreshold(new fast_9));
    else if(d == "fast9old")
        return auto_ptr<DetectN>(new SearchThreshold(new fast_9_old));
    else if(d == "fast12")
        return auto_ptr<DetectN>(new SearchThreshold(new fast_12));
    else if(d == "faster2")
        return auto_ptr<DetectN>(new SearchThreshold(new faster_learn(GV3::get<string>("faster2"))));
    else
    {
        cerr << "Unknown detector: " << d << endl;
        exit(1);
    }
}
void HarrisDetector (const CVD::Image< float > & i, std::vector< std::pair< float, CVD::ImageRef > > & c, unsigned int N, float blur, float sigmas)
Detect Harris corners.
Parameters:
i Image in which to detect corners
c Detected corners and strengths are inserted in to this container
N Number of corners to detect
blur Standard deviation of blur to use
sigmas Blur using sigmas standard deviations
Referenced by harrisdog::operator()().