FAST-ER: Repeatability dataset
Repeatability dataset
Detailed Description
To compute repeatability, you must know for every pixel in image A, where that pixel ends up in image B.
The datasets are stored internally as:
Images are simply stored internally as: vector<Image<byte> >
Mappings from A to B are stored as: vector<vector<array<float, 2> > > so mapping[i][j][y][x], is where pixel in image i should appear in image j
These datasets can be stored in disk in several formats. However, they are loaded by a single function, load_data(string, int, string) In all datasets, all images must be the same size.
The consists of N images, and an arbitrary warp for each image pair. From some base directory, the files are stored as:
frames/frame_x.pgm
warps/warp_i_j.warp The warp files have the mapping positions stored in row-major format, one pixel per line, stored as a pair of real numbers in text format. Details are in load_warps_cambridge() and load_images_cambridge(). The indices, x, i and j count from zero.
This stores the warp data in 16 bit per channel (with a numeric range of 0--65535), colour PNG format:
frames/frame_x.pgm
pngwarps/warp_i_j.png The destination of the x coordinare is stored as , and the y destination as . MULTIPLIER is 64.0 and SHIFT is 10.0 The blue channel stores nothing. Details are in load_warps_cambridge_png().
The executable warp_to_png.cc converts a .warp file to a .png file.
The datasets consist on N images and N-1 Homographies describing the warps between images the first and Nth image. The first homography is therefore the identity matrix.
From a base directory, the files are:
H1toip
imgi.ppm
where the index i counts from 1. More details are in load_warps_cambridge_png() and load_images_vgg().
Functions
vector< Image< byte > > load_images_cambridge (string dir, int n, string suffix)
vector< Image< byte > > load_images_vgg (string dir, int n)
vector< vector
< Image< array
< float, 2 > > > > load_warps_cambridge_png (string dir, int num, ImageRef size)
vector< vector
< Image< array
< float, 2 > > > > load_warps_cambridge (string dir, int num, ImageRef size)
vector< vector
< Image< array
< float, 2 > > > > load_warps_vgg (string dir, int num, ImageRef size)
pair< vector< Image
< byte > >, vector
< vector< Image
< array< float, 2 > > > > > load_data (string dir, int num, string format)
void prune_warps (vector< vector< Image< array< float, 2 > > > > &warps, ImageRef size)
Function Documentation
vector<Image<byte> > load_images_cambridge (string dir, int n, string suffix)
Load images from a "Cambridge" style dataset.
Parameters:
dir The base directory of the dataset.
n The number of images in the dataset.
suffix Image filename suffix to use.
Returns:
The loaded images.
Definition at line 49 of file load_data.cc.
Referenced by load_data().
{
    dir += "/frames/frame_%i." + suffix;
    vector<Image<byte> > ret;
    for(int i=0;  i < n; i++)
    {
        Image<byte> im;
        im = img_load(sPrintf(dir, i));
        ret.push_back(im);
    }
    return ret;
}
vector<Image<byte> > load_images_vgg (string dir, int n)
Load images from an "Oxford VGG" style dataset.
Parameters:
dir The base directory of the dataset.
n The number of images in the dataset.
Returns:
The loaded images.
Definition at line 72 of file load_data.cc.
Referenced by load_data().
{
    dir += "/img%i.ppm";
    vector<Image<byte> > ret;
    for(int i=0;  i < n; i++)
        ret.push_back(img_load(sPrintf(dir, i+1)));
    return ret;
}
vector<vector<Image<array<float,2> > > > load_warps_cambridge_png (string dir, int num, ImageRef size)
Load warps from a "Cambridge" repeatability dataset, with the warps stored encoded in PNG files.
See load_warps_cambridge
Parameters:
dir The base directory of the dataset.
num The numbers of images in the dataset.
size The size of the corresponding images.
Returns:
return_value[i][j][y][x] is where pixel x, y in image i warps to in image j.
Definition at line 113 of file load_data.cc.
Referenced by load_data().
{
    dir += "/pngwarps/warp_%i_%i.png";
    vector<vector<Image<array<float, 2> > > > ret(num, vector<Image<array<float, 2> > >(num));
    BasicImage<byte> tester(NULL, size);
    array<float, 2> outside((TupleHead, -1, -1));
    for(int from = 0; from < num; from ++)
        for(int to = 0; to < num; to ++)
            if(from != to)
            {
                string fname = sPrintf(dir, from, to);
                Image<Rgb<unsigned short> > p = img_load(fname);
                if(p.size() != size)
                {
                    cerr << "Error: warp file " << fname << " is the wrong size!\n";
                    exit(1);
                }
                Image<array<float,2> > w(size, outside);
                for(int y=0; y < size.y; y++)
                    for(int x=0; x < size.x; x++)
                    {
                        w[y][x][0] = p[y][x].red / MULTIPLIER - SHIFT;
                        w[y][x][1] = p[y][x].green / MULTIPLIER - SHIFT;
                    }
                cerr << "Loaded " << fname << endl;
                ret[from][to] = w;
            }
    return ret;
}
vector<vector<Image<array<float,2> > > > load_warps_cambridge (string dir, int num, ImageRef size)
Load warps from a "Cambridge" repeatability dataset.
The dataset contains warps which round to outside the image by one pixel in the max direction.
Note that the line labelled "prune" is diasbled in the evaluation of the FAST-ER system. This causes the two systems to produce slightly different results. If this line is commented out, then FAST-ER generated detectors produce exactly the same results when loaded back in to this system.
Parameters:
dir The base directory of the dataset.
num The numbers of images in the dataset.
size The size of the corresponding images.
Returns:
return_value[i][j][y][x] is where pixel x, y in image i warps to in image j.
Definition at line 168 of file load_data.cc.
Referenced by load_data().
{
    dir += "/warps/warp_%i_%i.warp";
    vector<vector<Image<array<float, 2> > > > ret(num, vector<Image<array<float, 2> > >(num));
    BasicImage<byte> tester(NULL, size);
    array<float, 2> outside((TupleHead, -1, -1));
    for(int from = 0; from < num; from ++)
        for(int to = 0; to < num; to ++)
            if(from != to)
            {
                Image<array<float,2> > w(size, outside);
                int n = size.x * size.y;
                Image<array<float,2> >::iterator p = w.begin();
                ifstream f;
                string fname = sPrintf(dir, from, to);
                f.open(fname.c_str());
                if(!f.good())
                {
                    cerr << "Error: " << fname << ": " << strerror(errno) << endl;
                    exit(1);
                }
                array<float, 2> v;
                for(int i=0; i < n; ++i, ++p)
                {
                    f >> v;
                    //prune
                    //if(v[0] >= 0 && v[1] >= 0 && v[0] <= size.x-1 && v[1] <= size.y-1)
                        *p = v;
                }
                if(!f.good())
                {
                    cerr << "Error: " << fname << " went bad" << endl;
                    exit(1);
                }
                cerr << "Loaded " << fname << endl;
                ret[from][to] = w;
            }
    return ret;
}
vector<vector<Image<array<float, 2> > > > load_warps_vgg (string dir, int num, ImageRef size)
Load warps from an "Oxford VGG" repeatability dataset.
The warps are stored as homographies, so warps need to be generated.
Parameters:
dir The base directory of the dataset.
num The numbers of images in the dataset.
size The size of the corresponding images.
Returns:
return_value[i][j][y][x] is where pixel x, y in image i warps to in image j.
Definition at line 238 of file load_data.cc.
References Arr(), and invert().
Referenced by load_data().
{
    dir += "/H1to%ip";
    array<float, 2> outside((TupleHead, -1, -1));
    //Load the homographies
    vector<Matrix<3> > H_1_to_x;
    //The first homography is always the identity.
    {
        Matrix<3> i;
        Identity(i);
        H_1_to_x.push_back(i);
    }
    for(int i=2; i <= num; i++)
    {
        ifstream f;
        string fname = sPrintf(dir, i).c_str();
        f.open(fname.c_str());
        Matrix<3> h;
        f >> h;
        if(!f.good())
        {
            cerr << "Error: " << fname << " went bad" << endl;
            exit(1);
        }
        H_1_to_x.push_back(h);
    }
    vector<vector<Image<array<float, 2> > > > ret(num, vector<Image<array<float, 2> > >(num));
    //Generate the warps.
    for(int from = 0; from < num; from ++)
        for(int to = 0; to < num; to ++)
            if(from != to)
            {
                Matrix<3> from_to_one = invert(H_1_to_x[from]);
                Matrix<3> one_to_to   = H_1_to_x[to];
                Matrix<3> from_to_to = one_to_to * from_to_one;
                Image<array<float,2> > w(size, outside);
                for(int y=0; y < size.y; y++)
                    for(int x=0; x < size.x; x++)
                    {
                        Vector<2> p = project(from_to_to * Vector<3>((make_Vector, x, y, 1)));
                        if(p[0] >= 0 && p[1] >= 0 && p[0] <= size.x-1 && p[1] <= size.y-1)
                            w[y][x] = Arr(p);
                    }
                ret[from][to] = w;
                cerr << "Created warp " << from << " -> " << to << endl;
            }
    return ret;
}
pair<vector<Image<byte> >, vector<vector<Image<array<float, 2> > > > > load_data (string dir, int num, string format)
Load a dataset.
Parameters:
dir The base directory of the dataset.
num The number of images in the dataset.
format The type of the dataset. This should be one of `vgg', `cam-png' or `cam'.
Returns:
The images and the warps.
Definition at line 316 of file load_data.cc.
References load_images_cambridge(), load_images_vgg(), load_warps_cambridge(), load_warps_cambridge_png(), and load_warps_vgg().
Referenced by main(), mmain(), and run_learn_detector().
{
    vector<Image<byte> > images;
    vector<vector<Image<array<float, 2> > > > warps;
    DataFormat d;
    if(format == "vgg")
        d = VGG;
    else if(format == "cam-png")
        d = CambridgePNGWarp;
    else
        d = Cambridge;
    switch(d)
    {
        case Cambridge:
            images = load_images_cambridge(dir, num, "pgm");
            break;
        case CambridgePNGWarp:
            images = load_images_cambridge(dir, num, "png");
            break;
        case VGG:
            images = load_images_vgg(dir, num);
    };
    //Check for sanity
    if(images.size() == 0)
    {
        cerr << "No images!\n";
        exit(1);
    }
    for(unsigned int i=0; i < images.size(); i++)
        if(images[i].size() != images[0].size())
        {
            cerr << "Images are different sizes!\n";
            exit(1);
        }
    switch(d)
    {
        case CambridgePNGWarp:
            warps = load_warps_cambridge_png(dir, num, images[0].size());
            break;
        case Cambridge:
            warps = load_warps_cambridge(dir, num, images[0].size());
            break;
        case VGG:
            warps = load_warps_vgg(dir, num, images[0].size());
    };
    return make_pair(images, warps);
}
void prune_warps (vector< vector< Image< array< float, 2 > > > > & warps, ImageRef size)
This function prunes a dataset so that no warped point will lie outside an image.
This will save on .in_image() tests later.
Parameters:
warps The warps to prune.
size the image size to prune to.
Definition at line 384 of file load_data.cc.
References ir_rounded().
Referenced by run_learn_detector().
{
    BasicImage<byte> test(NULL, size);
    array<float, 2> outside = make_tuple(-1, -1);
    for(unsigned int i=0; i < warps.size(); i++)
        for(unsigned int j=0; j < warps[i].size(); j++)
        {
            for(Image<array<float, 2> >::iterator  p=warps[i][j].begin(); p != warps[i][j].end(); p++)
                if(!test.in_image(ir_rounded(*p)))
                    *p = outside;
        }
}