FAST-ER: Utility functions.
Utility functions.
Defines
#define fatal(E, S,...) vfatal((E), (S), (tag::Fmt,## __VA_ARGS__))
Functions
vector< string > split (const string &s)
template<class C>
C ato (const string &s)
double sq (double d)
vector< int > range (int num)
template<class C>
void vfatal (int err, const string &s, const C &list)
istream & operator>> (istream &i, array< float, 2 > &f)
array< float, 2 > Arr (const Vector< 2 > &vec)
Matrix< 3 > invert (const Matrix< 3 > &m)
void draw_offset_list (const vector< ImageRef > &offsets)
void draw_offsets ()
CVD::ImageRef ir_rounded (const tag::array< float, 2 > &v)
Define Documentation
#define fatal (E, S, ...) vfatal((E), (S), (tag::Fmt,## __VA_ARGS__))
Print an error message and the exit.
Parameters:
E Error code
S Format string
Definition at line 125 of file learn_fast_tree.cc.
Referenced by find_best_split(), load_features(), main(), and datapoint< FEATURE_SIZE >::pack_trits().
Function Documentation
vector<string> split (const string & s)
Tokenise a string.
Parameters:
s String to be split
Returns:
Tokens
Definition at line 249 of file faster_tree.cc.
Referenced by load_a_tree().
{
    istringstream i(s);
    vector<string> v;
    while(!i.eof())
    {
        string s;
        i >> s;
        if(s != "")
            v.push_back(s);
    }
    return v;
}
template<class C> C ato (const string & s) [inline]
String to some class.
Name modelled on atoi.
Parameters:
s String to parse
Returns:
class the string was parsed in to.
Definition at line 269 of file faster_tree.cc.
{
    istringstream i(s);
    C c;
    i >> c;
    if(i.bad())
        throw   ParseError();
    return c;
}
double sq (double d)
Square a number.
Parameters:
d Number to square
Returns:
$d^2$
Definition at line 100 of file learn_detector.cc.
Referenced by learn_detector().
{
    return d*d;
}
vector<int> range (int num)
Populate a std::vector with the numbers 0,1,.
..,num
Parameters:
num Size if the range
Returns:
the populated vector.
Definition at line 110 of file learn_detector.cc.
{
    vector<int> r;
    for(int i=0; i < num; i++)
        r.push_back(i);
    return r;
}
template<class C> void vfatal (int err, const string & s, const C & list) [inline]
Print an error message and the exit, using Tuple stype VARARGS.
Parameters:
err Error code
s Format string
list Argument list
Definition at line 131 of file learn_fast_tree.cc.
{
    vfPrintf(cerr, s + "\n", list);
    exit(err);
}
istream& operator>> (istream & i, array< float, 2 > & f)
Load an array from an istream.
Parameters:
i Stream to load from
f array to load in to
Definition at line 88 of file load_data.cc.
{
    i >> f[0] >> f[1];
    return i;
}
array<float, 2> Arr (const Vector< 2 > & vec)
Convert a vector in to an array.
Parameters:
vec Vector to convert
Definition at line 97 of file load_data.cc.
Referenced by load_warps_vgg().
{
    return array<float, 2>((TupleHead, vec[0], vec[1]));
}
Matrix<3> invert (const Matrix< 3 > & m)
Invert a matrix.
Parameters:
m Matrix to invert
Definition at line 223 of file load_data.cc.
Referenced by tree_element::detect_corner(), load_warps_vgg(), and tree_element::make_fast_detector().
{
    LU<3> i(m);
    return i.get_inverse();
}
void draw_offset_list (const vector< ImageRef > & offsets)
Pretty print some offsets to stdout.
Parameters:
offsets List of offsets to pretty-print.
Definition at line 91 of file offsets.cc.
Referenced by draw_offsets().
{
    cout << "Allowed offsets: " << offsets.size() << endl;
    ImageRef min, max;
    min.x = *min_element(member_iterator(offsets.begin(), &ImageRef::x), member_iterator(offsets.end(), &ImageRef::x));
    max.x = *max_element(member_iterator(offsets.begin(), &ImageRef::x), member_iterator(offsets.end(), &ImageRef::x));
    min.y = *min_element(member_iterator(offsets.begin(), &ImageRef::y), member_iterator(offsets.end(), &ImageRef::y));
    max.y = *max_element(member_iterator(offsets.begin(), &ImageRef::y), member_iterator(offsets.end(), &ImageRef::y));
    cout << print << min <<max << endl;
    Image<int> o(max-min+ImageRef(1,1), -1);
    for(unsigned int i=0; i <offsets.size(); i++)
        o[offsets[i] -min] = i;
    for(int y=0; y < o.size().y; y++)
    {
        for(int x=0; x < o.size().x; x++)
            cout << "+------";
        cout << "+"<< endl;
        for(int x=0; x < o.size().x; x++)
            cout << "|      ";
        cout << "|"<< endl;
        for(int x=0; x < o.size().x; x++)
        {
            if(o[y][x] >= 0)
                cout << "|  " << setw(2) << o[y][x] << "  ";
            else if(ImageRef(x, y) == o.size() / 2)
                cout << "|   " << "#" << "  ";
            else
                cout << "|      ";
        }
        cout <<  "|" << endl;
        for(int x=0; x < o.size().x; x++)
            cout << "|      ";
        cout << "|"<< endl;
    }
    for(int x=0; x < o.size().x; x++)
        cout << "+------";
    cout << "+"<< endl;
    cout << endl;
}
void draw_offsets ()
Prettyprints the contents of offsets.
Definition at line 201 of file offsets.cc.
Referenced by run_learn_detector().
{
    //Print the offsets out.
    for(unsigned int i=0; i < 8; i++)
    {
        cout << "Offsets " << i << endl;
        draw_offset_list(offsets[i]);
        cout << endl;
    }
}
CVD::ImageRef ir_rounded (const tag::array< float, 2 > & v) [inline]
Convert a float array into an image co-ordinate.
Numbers are rounded
Parameters:
v The array to convert
Definition at line 30 of file utility.h.
Referenced by compute_repeatability(), prune_warps(), and transform_offsets().
{
    return CVD::ImageRef(
  static_cast<int>(v[0] > 0.0 ? v[0] + 0.5 : v[0] - 0.5),
  static_cast<int>(v[1] > 0.0 ? v[1] + 0.5 : v[1] - 0.5));
}