FAST-ER: faster_learn Struct Reference
faster_learn Struct Reference
[Functions for detecting corners of various types.]
#include <faster_detector.h>
Detailed Description
FAST-ER detector.
Definition at line 36 of file faster_detector.h.
Public Member Functions
virtual void operator() (const CVD::Image< CVD::byte > &i, std::vector< CVD::ImageRef > &c, unsigned int N) const
faster_learn (const std::string &fname)
Private Attributes
std::auto_ptr
< tree_element > tree
Constructor & Destructor Documentation
faster_learn::faster_learn (const std::string & fname)
Initialize a detector.
Parameters:
fname File to load the detector from. This was created from learn_detector.
Definition at line 72 of file faster_detector.cc.
References load_a_tree(), and block_bytecode::print().
{
    init();
    ifstream i;
    i.open(fname.c_str());
    if(!i.good())
    {
        cerr << "Error: " << fname << ": " << strerror(errno) << endl;
        exit(1);
    }
    try{
        tree.reset(load_a_tree(i));
    }
    catch(ParseError p)
    {
        cerr << "Parse error in " << fname << endl;
        exit(1);
    }
    if(GV3::get<bool>("faster_tree.print_tree", 0, 1))
    {
        clog << "Tree:" << endl;
        tree->print(clog);
    }
    if(GV3::get<bool>("faster_tree.print_block", 0, 1))
    {
        block_bytecode f2 = tree->make_fast_detector(100);
        f2.print(clog,  100);
    }
}
Member Function Documentation
void faster_learn::operator() (const CVD::Image< CVD::byte > & i, std::vector< CVD::ImageRef > & c, unsigned int N) const [virtual]
Detect corners.
Parameters:
i Image in which to detect corners
c Detected corners are inserted in to this container
N Threshold used to detect corners
Implements DetectT.
Definition at line 107 of file faster_detector.cc.
References tree_detect_corners().
{
    Image<int> scratch(i.size(), 0);
    v = tree_detect_corners(i, tree.get(), t, scratch);
}
Member Data Documentation
std::auto_ptr<tree_element> faster_learn::tree [private]
Loaded FAST-ER tree.
Definition at line 50 of file faster_detector.h.
The documentation for this struct was generated from the following files:
faster_detector.h
faster_detector.cc